//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellingBags.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SellingBagsEntities : DbContext
    {
        public SellingBagsEntities()
            : base("name=SellingBagsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Discount> Discounts { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductType> ProductTypes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<WishList> WishLists { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Shipping> Shippings { get; set; }
    
        public virtual ObjectResult<spLoadAllBrand_Result> spLoadAllBrand()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spLoadAllBrand_Result>("spLoadAllBrand");
        }
    
        public virtual ObjectResult<spProductsByType_Result> spProductsByType(string iD_Category)
        {
            var iD_CategoryParameter = iD_Category != null ?
                new ObjectParameter("ID_Category", iD_Category) :
                new ObjectParameter("ID_Category", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spProductsByType_Result>("spProductsByType", iD_CategoryParameter);
        }
    
        public virtual ObjectResult<string> spLastCustomer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spLastCustomer");
        }
    
        public virtual int ReloadOrders()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ReloadOrders");
        }
    
        public virtual ObjectResult<Nullable<decimal>> spMonthlyRevenue(Nullable<int> month)
        {
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("spMonthlyRevenue", monthParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> spYearlyRevenue(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("spYearlyRevenue", yearParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> spDaylyRevenue(Nullable<System.DateTime> today)
        {
            var todayParameter = today.HasValue ?
                new ObjectParameter("today", today) :
                new ObjectParameter("today", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("spDaylyRevenue", todayParameter);
        }
    
        public virtual ObjectResult<spBestSeller_Result> spBestSeller(Nullable<int> month)
        {
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBestSeller_Result>("spBestSeller", monthParameter);
        }
    
        public virtual ObjectResult<spNewProduct_Result> spNewProduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spNewProduct_Result>("spNewProduct");
        }
    }
}
